### ISSUE TITLE
500 and 600 instances

### ISSUE THREAD

**Issue by davelab6** [impallari/Amika-Devanagari#5]
I think its useful to provide intermediate instances; as you've designed 400 and 700 masters, I propose 500 and 600 instances could be useful :)

**Comment by impallari** [comment]
Master are compatible, so it's no problem doing it.
However I'll suggest doing only 1 intermediate instance, instead of 2.

Adding 2 instances, the the stem jump from each weight to the next will be around 15 units.
Barely noticeable. Not sure if it will useful.

Adding 1 instance, the stem jump is around 22 units. Makes more sense IMHO.

Which option do you prefer?

**Comment by davelab6** [comment]
I guess a 600 is better than 500 if it is just 1

**Comment by impallari** [comment]
Ok
